name: PR check
on:
  pull_request:
    branches: [main]
jobs:
  react-diagrams:
    runs-on: ubuntu-latest
    steps:
      - run: nvm install
      - uses: actions/checkout@v1
      - run: yarn install --frozen-lockfile
      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: "packages/react-diagrams"
          package-manager: yarn
  react-diagrams-docs:
    runs-on: ubuntu-latest
    steps:
      - run: nvm install
      - uses: actions/checkout@v1
      run: |
        cd packages/react-diagrams-docs
        yarn build
