name: PR check
on:
  pull_request:
    branches: [main]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: yarn install --frozen-lockfile
      - run: yarn test:ci
      - uses: artiomtr/jest-coverage-report-action@v1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: packages/react-diagrams
          package-manager: yarn
